language: c
os:
  - linux
#  - osx
env:
  matrix:
    - JULIAVERSION="https://status.julialang.org/download/linux-i686"
    - JULIAVERSION="https://status.julialang.org/download/linux-x86_64"
#julia:
#  - release
#  - nightly
#sudo: false
addons:
  apt_packages:
#  - gcc-multilib
  - zlib1g:i386
notifications:
  email: false
script:
  - mkdir -p ~/julia
  - curl -L $JULIAVERSION | tar -C ~/julia -x -z --strip-components=1 -f -
  - export PATH=$PATH:$HOME/julia/bin
  - ls -al ~/julia/bin
  - file ~/julia/bin/*
  - ldd ~/julia/bin/julia
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("DataFrames"); Pkg.test("DataFrames"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("DataFrames")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
